Doing a GLMM when your (fixed effects) levels have unequal variances
====================================================================

```{r}
library(lmerTest)
library(ggplot2)
library(tidyr)
library(dplyr)
```

### Data

Simulate data.

```{r}
# There are three levels in my fixed effect
groups = c('A','B','C')

# Each level has its own mean
means = rep(c(100,150,200), each = 10)

# Levels' standard deviations vary wildly
sds = rep(c(4,65,70), each = 10)

# Individuals are nested within group, and each is present twice
indivs = rep(1:15,each = 2)

# The effect of individual on mean
re = rnorm(15,5,5)
means = means + rep(re,each = 2)

# Simulate the data
df = data.frame(GroupID = rep(groups, each = 10),
				Meas = rnorm(30,mean = means, sd = sds),
				Indiv = factor(indivs))
```

Look at it

```{r}
p = ggplot(df, aes(x = GroupID, y = Meas)) +
	geom_boxplot()
p
```

### Model

No accounting for unequal variances

```{r}
m1 = lmer(Meas ~ GroupID + (1|Indiv),df)
```

Account for unequal variances

```{r}
# Set up dummy variables for the two groups
df$DM1 = factor(ifelse(df$GroupID == 'B',1,0))
df$DM2 = factor(ifelse(df$GroupID == 'C',1,0))

# (equivalently:)
df$DM1 = dummy(df$GroupID,"B")
df$DM2 = dummy(df$GroupID,"C")

df$obs = factor(seq(nrow(df)))


# model
m2 = lmer(Meas ~ GroupID + (1|Indiv) + 
			## Deal with residual variance in B and C
			(0 + DM1|obs) + (0 + DM2|obs),
			df,
			## Stop lmer complaining
			control=lmerControl(check.nobs.vs.nRE="ignore",
								check.nobs.vs.nlev="ignore"))

# look
summary(m1)
summary(m2)
```

### Predicted vs. Residuals

```{r}
# First Model
preddf1 = expand.grid(GroupID = groups)
preddf1$Meas = predict(m1,preddf1,re.form=NA)
mm1 = model.matrix(terms(m1),preddf1)
pvar1 = diag(mm1 %*% tcrossprod(vcov(m1),mm1))
tvar1 = pvar1 + VarCorr(m1)$Indiv[1]
cmult = 1.96
preddf1 = data.frame(preddf1,
					 plo = preddf1$Meas - cmult*sqrt(pvar1),
					 phi = preddf1$Meas + cmult*sqrt(pvar1),
					 tlo = preddf1$Meas - cmult*sqrt(tvar1),
					 thi = preddf1$Meas + cmult*sqrt(tvar1))

# Second Model
preddf2 = expand.grid(GroupID = groups)
preddf2$Meas = predict(m2,preddf2,re.form=NA)
mm2 = model.matrix(terms(m2),preddf2)
pvar2 = diag(mm2 %*% tcrossprod(vcov(m2),mm2))
tvar2 = pvar2 + VarCorr(m2)$Indiv[1]
cmult = 1.96
preddf2 = data.frame(preddf2,
					 plo = preddf2$Meas - cmult*sqrt(pvar2),
					 phi = preddf2$Meas + cmult*sqrt(pvar2),
					 tlo = preddf2$Meas - cmult*sqrt(tvar2),
					 thi = preddf2$Meas + cmult*sqrt(tvar2))
preddf1
preddf2
```

Plot it

```{r}
p1 = ggplot(df, aes(x = GroupID, y = Meas)) +
	geom_boxplot(width = 0.6, position = position_dodge(width = 0.75)) +
	geom_linerange(data = preddf1, 
				   mapping = aes(x = GroupID,
				   					ymin = tlo,
				   			  		ymax = thi),
					inherit.aes = FALSE,
					position = position_dodge(width = 0.75),
					size = 2.5,
					colour = 'red',
					alpha = 0.3) +
	geom_point(data = preddf1,
				mapping = aes(x = GroupID,
								y = Meas),
				position = position_dodge(width = 0.75),
				size = 2.5,
				alpha = 0.7,
				colour = 'red')
p1

p2 = ggplot(df, aes(x = GroupID, y = Meas)) +
	geom_boxplot(width = 0.6, position = position_dodge(width = 0.75)) +
	geom_linerange(data = preddf2, 
				   mapping = aes(x = GroupID,
				   					ymin = tlo,
				   			  		ymax = thi),
					inherit.aes = FALSE,
					position = position_dodge(width = 0.75),
					size = 2.5,
					colour = 'red',
					alpha = 0.3) +
	geom_point(data = preddf2,
				mapping = aes(x = GroupID,
								y = Meas),
				position = position_dodge(width = 0.75),
				size = 2.5,
				alpha = 0.7,
				colour = 'red')
p2
```

Predicted vs. Residuals

```{r}
predred1 = data.frame(Predicted = predict(m1),
					  Residuals = resid(m1))
predred1 = data.frame(predred1,df)

p1 = ggplot(predred1, aes(x = Predicted, y = Residuals, colour = GroupID)) +
	geom_point() 

p1

predred2 = data.frame(Predicted = predict(m2),
					  Residuals = resid(m2))
predred2 = data.frame(predred2,df)

p2 = ggplot(predred2, aes(x = Predicted, y = Residuals, colour = GroupID)) +
	geom_point() 

p2

predred = rbind(predred1,predred2)
predred$Model = rep(c('m1','m2'), each = nrow(predred1))

p = ggplot(predred, aes(x = Predicted, y = Residuals,
						shape = Model, colour = GroupID)) + geom_point()
p

predred %>% group_by(GroupID,Model) %>%
	summarize(Mean = mean(Predicted))
```


















